sonar.projectKey=skillpulse
sonar.projectName=SkillPulse DevOps Masterclass
sonar.sources=backend,frontend
sonar.exclusions=docs/**,terraform/**,k8s/**,mysql/**,**/*_test.go
sonar.tests=backend
sonar.test.inclusions=**/*_test.go
sonar.sourceEncoding=UTF-8

