apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: skillpulse
  namespace: argocd
spec:
  description: SkillPulse GitOps project
  sourceRepos:
    - '*'
  destinations:
    - namespace: skillpulse
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

